name: FTP Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload to cPanel via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.CPANEL_FTP_PORT }}
        #   local-dir: visaprocessing.travelsansr.com/
        #   server-dir: visaprocessing.travelsansr.com/
